apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qkfjy8ipo-python 
  janus-idp.io/tekton: qkfjy8ipo-python
  backstage.io/kubernetes-id: qkfjy8ipo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qkfjy8ipo-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml